#!/usr/bin/env ruby
# frozen_string_literal: true
#
# configure-signing.rb
#
# Sets the Apple developer team and MANUAL App Store signing on the app target.
#
# Manual rather than automatic, and not by preference. Automatic signing asks
# Apple for a DEVELOPMENT profile when archiving, and Apple will not issue one
# to a team with no registered devices, so the archive fails outright on an
# account that has never had a device added. Setting an identity by hand then
# conflicts with the automatic style, so the whole thing has to be manual: an
# explicit distribution certificate and an App Store profile.
#
# That lesson is BOFFIN's, paid for there and applied here rather than repeated.
#
# IDEMPOTENT. Re-run after any change to the project's signing.
#
#   ruby Tools/configure-signing.rb

require "xcodeproj"

ROOT = File.expand_path("..", __dir__)
PROFILE = "JUMPjet App Store"

# The team id comes from the environment, never from this file, because this
# repository is public. It is not a secret in any strong sense (it appears in
# every provisioning profile and app receipt), but an account identifier does
# not belong in a public repo, and keeping it out means the project builds
# under any team rather than only this one.
#
#   set -a; source ~/.claude/skills/marcs-vibe-coding/credentials.env; set +a
TEAM = ENV["APPLE_TEAM_ID"].to_s
abort("APPLE_TEAM_ID is not set. Source your credentials file first.") if TEAM.empty?

# Xcode cannot read the environment, so the value is written to a gitignored
# xcconfig and the project refers to it as $(APPLE_TEAM_ID). A GUI build then
# works exactly like a command-line one.
CONFIG_DIR = File.join(ROOT, "Config")
CONFIG_PATH = File.join(CONFIG_DIR, "Signing.xcconfig")
Dir.mkdir(CONFIG_DIR) unless Dir.exist?(CONFIG_DIR)
File.write(CONFIG_PATH, <<~XCCONFIG)
  // Generated by Tools/configure-signing.rb. Gitignored: it carries the team id.
  // Regenerate with: set -a; source ~/.claude/skills/marcs-vibe-coding/credentials.env; set +a
  //                  ruby Tools/configure-signing.rb
  APPLE_TEAM_ID = #{TEAM}
XCCONFIG

project = Xcodeproj::Project.open(File.join(ROOT, "JUMPjet.xcodeproj"))
app = project.targets.find { |t| t.name == "JUMPjet" } or abort "no JUMPjet target"

# Attach the xcconfig at project level so every target inherits APPLE_TEAM_ID.
group = project.main_group["Config"] || project.main_group.new_group("Config", "Config")
ref = group.files.find { |f| f.path.to_s.end_with?("Signing.xcconfig") } ||
      group.new_reference("Signing.xcconfig")
project.build_configurations.each { |c| c.base_configuration_reference = ref }

app.build_configurations.each do |config|
  settings = config.build_settings
  settings["DEVELOPMENT_TEAM"] = "$(APPLE_TEAM_ID)"

  if config.name == "Release"
    settings["CODE_SIGN_STYLE"] = "Manual"
    # Xcode's default when nothing is set is "Apple Development", which cannot
    # sign an App Store archive. Naming the distribution identity explicitly is
    # what stops Release quietly resolving to the wrong one.
    settings["CODE_SIGN_IDENTITY"] = "Apple Distribution"
    settings["CODE_SIGN_IDENTITY[sdk=iphoneos*]"] = "Apple Distribution"
    settings["PROVISIONING_PROFILE_SPECIFIER"] = PROFILE
  else
    # Debug stays automatic so a simulator build needs nothing from Apple.
    settings["CODE_SIGN_STYLE"] = "Automatic"
    settings.delete("PROVISIONING_PROFILE_SPECIFIER")
  end
end

# The test bundles are never distributed, so they stay automatic. Left explicit
# because an archive that tries to provision them fails for a reason that reads
# as being about the app.
%w[JUMPjetTests JUMPjetUITests].each do |name|
  target = project.targets.find { |t| t.name == name } or next
  target.build_configurations.each do |config|
    config.build_settings["DEVELOPMENT_TEAM"] = "$(APPLE_TEAM_ID)"
    config.build_settings["CODE_SIGN_STYLE"] = "Automatic"
    config.build_settings["CODE_SIGN_IDENTITY"] = ""
  end
end

project.save

puts "team:    $(APPLE_TEAM_ID) -> #{TEAM}  (from Config/Signing.xcconfig, gitignored)"
app.build_configurations.each do |config|
  puts "  #{config.name.ljust(8)} style=#{config.build_settings['CODE_SIGN_STYLE']} " \
       "identity=#{config.build_settings['CODE_SIGN_IDENTITY'] || '(default)'} " \
       "profile=#{config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] || '(none)'}"
end
